//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyFramework.Tools;
using UnityEngine;



public partial class JBJB
{
    
    [EasyBounderControl("GameObject")]
    public Transform GameObject;
    
    [SerializeField()]
    [EasyBounderControl("GameObject_2")]
    private EasyControl _gameObject_2;
    
    /// <summary>
    /// <para>sdf</para>
    /// <para>tyuty</para>
    /// </summary>
    [EasyBounderControl("asdgdfgh")]
    public EasyControl Asdgdfgh;
    
    /// <summary>
    /// <para>sfhkyiu</para>
    /// </summary>
    [EasyBounderControl("klert6hy")]
    public Transform Klert6hy;
    

#if UNITY_EDITOR
    /// <summary>
    /// <para>EasyControl的编辑器参数</para>
    /// <para>（不要在代码中使用，仅在编辑器中有效！）</para>
    /// </summary>
    [SerializeField()]
    private EasyControlEditorArgs _easyControlEditorArgs;
#endif
}
