//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyFramework;
using UnityEngine;



public partial class jhghjkjh : IViewModel
{
    
    [ByViewBinder("GameObject")]
    public Transform GameObject;
    
    /// <summary>
    /// <para>fsdfsdfsdr</para>
    /// </summary>
    [ByViewBinder("dgdfgdrger")]
    public Transform Dgdfgdrger;
    
    [SerializeField()]
    private ViewModelInfo _viewModelInfo;
    
    public ViewModelInfo Info
    {
        get
        {
            return this._viewModelInfo;
        }
        set
        {
            this._viewModelInfo = value;
        }
    }
}
