//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyFramework.Tools;
using UnityEngine;



public partial class TestViewModel
{
    
    [EasyBounderControl("GameObject")]
    public EasyControl GameObject;
    
    [SerializeField()]
    [EasyBounderControl("GameObject2")]
    private EasyControl _gameObject2;
    

#if UNITY_EDITOR
    /// <summary>
    /// <para>EasyControl的编辑器参数</para>
    /// <para>（不要在代码中使用，仅在编辑器中有效！）</para>
    /// </summary>
    [SerializeField()]
    private EasyControlEditorArgs _easyControlEditorArgs;
#endif
}
