//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by view controller of the EasyFramework.
//     这些代码由EasyFramework的视图控制器生成。
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     更改可能导致未定义行为，并在下次代码生成时丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using EasyFramework.ToolKit;
using UnityEngine;
using Sirenix.OdinInspector;

public partial class TestController : IViewController
{
    [SerializeField, PropertyOrder(100000f), AutoBinding, TitleGroup("Bindings")]
    private TestController _testController;
    
    [SerializeField, PropertyOrder(100001f), AutoBinding, TitleGroup("Bindings")]
    public Transform Dsfgdfg;
    
    [SerializeField, PropertyOrder(100002f), AutoBinding, TitleGroup("Bindings")]
    public GameObject Dsfgdfgs3r;
    
    [SerializeField, PropertyOrder(100003f), AutoBinding, TitleGroup("Bindings")]
    private SpriteRenderer _circle;


    [SerializeField, PropertyOrder(1000000f)]
    private ViewControllerConfig _viewControllerConfig;

    ViewControllerConfig IViewController.Config
    {
        get => _viewControllerConfig;
        set => _viewControllerConfig = value;
    }
}
