//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyFramework;
using UnityEngine;



public partial class TestViewModel : IViewModel
{
    
    [FromViewBinder()]
    public GameObject Oooo;
    
    [FromViewBinder()]
    public GameObject Oooogfdh;
    
    [FromViewBinder()]
    public GameObject Sadfsdf;
    
    [FromViewBinder()]
    public Component Kkkjjj;
    
    [SerializeField()]
    private ViewModelInfo _viewModelInfo;
    
    public ViewModelInfo Info
    {
        get
        {
            return this._viewModelInfo;
        }
        set
        {
            this._viewModelInfo = value;
        }
    }
}
